export type VenueSeed = {
  slug: string;
  name: string;
  kind: "RESTAURANT" | "CAFE" | "MARKET" | "CULTURAL";
  area: string;
  address: string;
  mapsQuery: string;
  lat?: number;
  lng?: number;
  phone?: string;
  website?: string;
  hours?: string;
  priceRange?: string;
  menuNotes?: string;
  description: string;
};

export const ISTANBUL_VENUES: VenueSeed[] = [
  {
    slug: "aksaray-mahalle",
    name: "محله آکسارای",
    kind: "CULTURAL",
    area: "aksaray",
    address: "Aksaray Mahallesi, Fatih/İstanbul",
    mapsQuery: "Aksaray Meydanı Fatih İstanbul",
    lat: 41.0106,
    lng: 28.953,
    description: "پاتوق اصلی ایرانی‌های استانبول. رستوران، مارکت و کافه دور همین میدان و خیابان نامق‌کمال جمع شده‌اند.",
  },
  {
    slug: "safir-aksaray",
    name: "رستوران سفیر — آکسارای",
    kind: "RESTAURANT",
    area: "aksaray",
    address: "Aksaray Mah., Namık Kemal Cad. No:23, Fatih/İstanbul",
    mapsQuery: "Safir İran Mutfağı Namık Kemal Caddesi 23 Aksaray İstanbul",
    lat: 41.0102,
    lng: 28.9524,
    phone: "+90 212 234 10 10",
    website: "https://safiriranianrestaurant.com",
    hours: "۱۱:۰۰–۲۴:۰۰",
    priceRange: "₺₺₺",
    menuNotes: "چلوکباب، جوجه، خورش ایرانی",
    description: "شعبه آکسارای سفیر. چلوکباب و غذای ایرانی در مرکز پاتوق ایرانی‌ها.",
  },
  {
    slug: "safir-sisli",
    name: "رستوران سفیر — شیشلی",
    kind: "RESTAURANT",
    area: "sisli",
    address: "Merkez, Abide-i Hürriyet Cd. No:171/A, Şişli/İstanbul",
    mapsQuery: "Safir Iranian Restaurant Abide-i Hürriyet Caddesi 171 Şişli",
    lat: 41.0635,
    lng: 28.9874,
    phone: "+90 212 234 10 10",
    website: "https://safiriranianrestaurant.com",
    hours: "۱۲:۰۰–۲۳:۰۰",
    priceRange: "₺₺₺",
    menuNotes: "چلوکباب و غذای ایرانی سمت اروپایی",
    description: "شعبه شیشلی سفیر. برای دورهمی در سمت اروپایی، دور از آکسارای.",
  },
  {
    slug: "asuman-aksaray",
    name: "رستوران آسمان",
    kind: "RESTAURANT",
    area: "aksaray",
    address: "Kemalpaşa Mah., Atatürk Bulvarı No:158, Fatih/İstanbul",
    mapsQuery: "Asuman İran Restaurant Atatürk Bulvarı 158 Aksaray",
    lat: 41.0124,
    lng: 28.9536,
    phone: "+90 212 511 27 37",
    website: "https://www.asumanrestaurant.com",
    hours: "۱۲:۰۰–۲۱:۰۰",
    description: "از قدیمی‌های آکسارای (از ۲۰۰۹). غذای خانگی ایرانی روبه‌روی مدرسه اوروچ‌قاضی.",
  },
  {
    slug: "nayeb-findikzade",
    name: "رستوران نایب — فندق‌زاده",
    kind: "RESTAURANT",
    area: "findikzade",
    address: "Millet Cad. No:79, Fındıkzade, Fatih/İstanbul",
    mapsQuery: "Nayeb Restaurant Millet Caddesi 79 Fındıkzade İstanbul",
    lat: 41.0108,
    lng: 28.9398,
    phone: "+90 212 587 68 46",
    hours: "۱۰:۰۰–۲۴:۰۰",
    description: "نایب در میدان فندق‌زاده. کافه-رستوران ایرانی روی Millet Caddesi.",
  },
  {
    slug: "reyhun-taksim",
    name: "رستوران ریحون",
    kind: "RESTAURANT",
    area: "taksim",
    address: "Tomtom Mah., Yeni Çarşı Cad. No:26/1, Beyoğlu/İstanbul",
    mapsQuery: "Reyhun Iranian Restaurant Yeni Çarşı Caddesi 26 Beyoğlu",
    lat: 41.0328,
    lng: 28.9772,
    phone: "+90 212 245 15 00",
    website: "https://www.reyhun.net",
    hours: "۱۲:۰۰–۲۳:۰۰",
    description: "از ۲۰۱۴ کنار گالاتاسرای. برای دورهمی بعد از استقلال، نه فقط گردشگر.",
  },
  {
    slug: "termeh-beyoglu",
    name: "رستوران ترمه",
    kind: "RESTAURANT",
    area: "taksim",
    address: "Tomtom, Yeni Çarşı Cd. No:8, 34433 Beyoğlu/İstanbul",
    mapsQuery: "Termeh Restaurant Yeni Çarşı Caddesi 8 Beyoğlu",
    lat: 41.033,
    lng: 28.9776,
    phone: "+90 212 243 14 02",
    hours: "۱۰:۰۰–۲۳:۰۰",
    description: "چند قدم پایین‌تر از ریحون. فضای چوبی و خودمانی برای ناهار یا شام ایرانی.",
  },
  {
    slug: "mojgan-taksim",
    name: "رستوران مژگان",
    kind: "RESTAURANT",
    area: "taksim",
    address: "Kocatepe, Abdülhak Hamit Cd. No:19/A, Beyoğlu/İstanbul",
    mapsQuery: "Mojgan Restaurant Abdülhak Hamit Caddesi 19 Beyoğlu",
    lat: 41.0374,
    lng: 28.9836,
    phone: "+90 212 533 82 00",
    hours: "۱۲:۰۰–۲۴:۰۰",
    description: "نزدیک تکسیم. قرمه‌سبزی و فسنجان در خیابان عبدالحق‌حمید.",
  },
  {
    slug: "shamse-istiklal",
    name: "رستوران شمسه",
    kind: "RESTAURANT",
    area: "taksim",
    address: "Tomtom, İstiklal Cd. No:179, Beyoğlu/İstanbul",
    mapsQuery: "Shamse Restaurant İstiklal Caddesi 179 Beyoğlu",
    lat: 41.0322,
    lng: 28.9764,
    phone: "+90 543 170 28 66",
    hours: "۱۱:۰۰–۱۴:۰۰ و عصرها",
    description: "روی استقلال. جای دیده‌شدن بعد از پیاده‌روی، نه کلاب شبانه.",
  },
  {
    slug: "safran-gumussuyu",
    name: "رستوران زعفران — گوموش‌سویو",
    kind: "RESTAURANT",
    area: "taksim",
    address: "Gümüşsuyu Mah., Asker Ocağı Cad. No:1 D:kat 15/B, Beyoğlu/İstanbul",
    mapsQuery: "Safran Iranian Restaurant Asker Ocağı Caddesi 1 Gümüşsuyu",
    lat: 41.0388,
    lng: 28.9882,
    phone: "+90 212 368 44 44",
    hours: "۱۸:۰۰–۲۳:۰۰",
    description: "شام ایرانی نزدیک تکسیم/گوموش‌سویو. بیشتر عصر و شب.",
  },
  {
    slug: "daryakenar-sisli",
    name: "رستوران دریاکنار",
    kind: "RESTAURANT",
    area: "sisli",
    address: "Ergenekon, Cumhuriyet Cd. No:151, Şişli/İstanbul",
    mapsQuery: "Daryakenar Restaurant Cumhuriyet Caddesi 151 Şişli",
    lat: 41.0526,
    lng: 28.9878,
    phone: "+90 537 349 81 01",
    hours: "۱۲:۳۰–۲۳:۳۰",
    description: "روی جمهوری، بین تکسیم و عثمان‌بی. شام دوستانه.",
  },
  {
    slug: "gulistan-sisli",
    name: "رستوران گلستان",
    kind: "RESTAURANT",
    area: "sisli",
    address: "Ergenekon, Papa Roncalli Sk. No:84, Şişli/İstanbul",
    mapsQuery: "Gulistan İran Restaurant Papa Roncalli Sokak 84 Şişli",
    lat: 41.0548,
    lng: 28.9864,
    phone: "+90 212 232 55 05",
    hours: "۰۸:۰۰–۲۴:۰۰",
    description: "شیشلی/ارگنکون. صبح تا دیروقت باز است؛ جای ناهار کاری هم هست.",
  },
  {
    slug: "golab-atakoy",
    name: "رستوران گلاب — آتاکوی مارینا",
    kind: "RESTAURANT",
    area: "atakoy",
    address: "Zeytinlik, Ataköy Marina, 34140 Bakırköy/İstanbul",
    mapsQuery: "Golab Restoran Ataköy Marina Bakırköy",
    lat: 40.9742,
    lng: 28.8754,
    phone: "+90 535 412 40 05",
    website: "https://golabrestaurant.com",
    hours: "۱۰:۰۰–۰۰:۰۰",
    description: "کنار آب در مارینای آتاکوی. برای دورهمی عصر جمعه با منظره، نه سوایپ.",
  },
  {
    slug: "shiraz-kadikoy",
    name: "رستوران شیراز — کادیکوی",
    kind: "RESTAURANT",
    area: "kadikoy",
    address: "Caferağa Mah., Sarraf Ali Sokak No:7/A, Kadıköy/İstanbul",
    mapsQuery: "Shiraz Restaurant Sarraf Ali Sokak 7 Kadıköy",
    lat: 40.9906,
    lng: 29.0248,
    phone: "+90 506 302 81 88",
    hours: "۱۵:۰۰–۲۴:۰۰",
    priceRange: "۲۵۰–۴۵۰ لیر",
    menuNotes: "کباب، خورش، چای بعد از غذا.",
    description: "سمت آسیا، پشت مودا/کادیکوی. رستوران ایرانی مناسب دورهمی عصر.",
  },
  {
    slug: "cheshmeh-kadikoy",
    name: "کافه کتاب چشمه",
    kind: "CULTURAL",
    area: "kadikoy",
    address: "Caferağa, Misak-ı Milli Sok. No:56A, Kadıköy/İstanbul",
    mapsQuery: "Cheshmeh İstanbul Misak-ı Milli Sokak 56A Kadıköy",
    lat: 40.9902,
    lng: 29.0262,
    phone: "+90 541 245 12 39",
    hours: "تا ۲۰:۰۰",
    description: "نمایندگی نشر چشمه. کافه-کتاب فارسی برای مطالعه و جمع فرهنگی کوتاه.",
  },
  {
    slug: "gilan-acibadem",
    name: "کافه رستوران گیلان",
    kind: "CAFE",
    area: "kadikoy",
    address: "Acıbadem Mah., Umut Sokak 3/D, İstanbul",
    mapsQuery: "Gilan Cafe Restaurant Umut Sokak Acıbadem İstanbul",
    lat: 41.0008,
    lng: 29.0406,
    phone: "+90 216 325 66 15",
    hours: "۰۹:۰۰–۲۲:۰۰",
    description: "غذای شمال ایران در آجی‌بادم. میرزاقاسمی و چای گیلانی.",
  },
  {
    slug: "tehroon-maslak",
    name: "مطبخ طهرون — ماسلاک",
    kind: "RESTAURANT",
    area: "maslak",
    address: "Maslak, Dereboyu 2 Cd. No:5 İç Kapı No:74, Şişli/İstanbul",
    mapsQuery: "Tehroon Restaurant Dereboyu 2 Caddesi 5 Maslak",
    lat: 41.1084,
    lng: 29.0068,
    phone: "+90 850 554 50 50",
    hours: "۱۲:۰۰–۲۳:۰۰",
    description: "ماسلاک برای کسانی که آن سمت شهر کار می‌کنند. خورش و جوجه‌کباب.",
  },
  {
    slug: "lalezaar-maslak",
    name: "کافه لاله‌زار",
    kind: "CAFE",
    area: "maslak",
    address: "Maslak, Dereboyu 2 Cd. No:76, Şişli/İstanbul",
    mapsQuery: "Café Lalezaar Dereboyu 2 Caddesi 76 Maslak",
    lat: 41.1102,
    lng: 29.0076,
    phone: "+90 212 559 11 11",
    hours: "۱۲:00–۰۰:۳۰",
    description: "کافه-رستوران ایرانی ماسلاک. میرزاقاسمی و فالوده بعد از کار.",
  },
  {
    slug: "zolfa-maslak",
    name: "رستوران زلفا (وگن)",
    kind: "RESTAURANT",
    area: "maslak",
    address: "Ahi Evran Cd. No:5, Sarıyer/İstanbul",
    mapsQuery: "Zolfa Iranian Vegan Restaurant Ahi Evran Caddesi 5 Maslak",
    lat: 41.1076,
    lng: 29.0092,
    phone: "+90 212 346 38 46",
    hours: "۱۲:۰۰–۲۳:۰۰",
    description: "ایرانی و گیاهی در ماسلاک/ساری‌یر. برای دورهمی بدون کباب هم جا هست.",
  },
  {
    slug: "arya-sariyer",
    name: "رستوران آریا",
    kind: "RESTAURANT",
    area: "sariyer",
    address: "Ayazağa, Kemerburgaz Cd. No:10, Sarıyer/İstanbul",
    mapsQuery: "Arya Restaurant Kemerburgaz Caddesi 10 Sarıyer",
    lat: 41.1184,
    lng: 28.9992,
    phone: "+90 552 839 80 80",
    hours: "۱۱:۰۰–۲۳:۵۰",
    description: "ساری‌یر/آیازآغا. شام شیک‌تر برای جمع کوچک.",
  },
  {
    slug: "sudi-atasehir",
    name: "رستوران سودی",
    kind: "RESTAURANT",
    area: "atasehir",
    address: "Atatürk Mah., Atapark Cad., Trendist Dükkan B11 Blok No:3/PA, Ataşehir/İstanbul",
    mapsQuery: "Sudi Restoran Trendist Ataşehir",
    lat: 40.9924,
    lng: 29.1272,
    phone: "+90 216 266 60 36",
    website: "https://www.sudirestoran.com",
    hours: "۱۱:۱۵–۲۲:۰۰",
    description: "آتاشهر، سمت آسیا. گاهی موسیقی زنده.",
  },
  {
    slug: "shandiz-maltepe",
    name: "رستوران شاندیز — مالتپه",
    kind: "RESTAURANT",
    area: "maltepe",
    address: "İdealtepe, Turgut Özal Blv. No:133, Maltepe/İstanbul",
    mapsQuery: "Shandiz Restaurant Turgut Özal Bulvarı 133 Maltepe",
    lat: 40.9356,
    lng: 29.1334,
    phone: "+90 532 280 02 46",
    hours: "۱۲:۰۰–۲۴:۰۰",
    description: "کباب شاندیز در مالتپه. برای ساکن‌های سمت آسیای جنوبی.",
  },
  {
    slug: "sevenkhan-kagithane",
    name: "رستوران هفت‌خوان",
    kind: "RESTAURANT",
    area: "kagithane",
    address: "Çağlayan Merkez, Seçkin Sk. 2-4/A, Kağıthane/İstanbul",
    mapsQuery: "7Khan Iranian Restaurant Seçkin Sokak Kağıthane",
    lat: 41.0802,
    lng: 28.9736,
    phone: "+90 538 291 46 56",
    hours: "۱۲:۰۰–۲۴:۰۰",
    description: "کاغیتخانه/چاغلایان. گاهی موسیقی زنده.",
  },
  {
    slug: "shahrzad-ortakoy",
    name: "رستوران شهرزاد — اورتاکوی",
    kind: "RESTAURANT",
    area: "besiktas",
    address: "Mecidiye Mah., Değirmen Sokak No:10, Ortaköy, Beşiktaş/İstanbul",
    mapsQuery: "Shahrzad Iranian Restaurant Değirmen Sokak 10 Ortaköy",
    lat: 41.0474,
    lng: 29.0268,
    phone: "+90 539 358 31 78",
    hours: "۱۲:۰۰–۲۳:۰۰",
    description: "اورتاکوی. شام کنار بسفر با فضای ایرانی.",
  },
  {
    slug: "kralice-ortakoy",
    name: "رستوران کرالیچه",
    kind: "RESTAURANT",
    area: "besiktas",
    address: "Ortaköy, Mecidiye, Eski Bahçe Sk. No:E D:2, Beşiktaş/İstanbul",
    mapsQuery: "Kraliçe Restaurant Eski Bahçe Sokak Ortaköy",
    lat: 41.0478,
    lng: 29.0256,
    phone: "+90 212 327 19 59",
    hours: "۱۲:۰۰–۲۴:۰۰",
    description: "اورتاکوی. کباب و دسر ایرانی نزدیک میدان.",
  },
  {
    slug: "keyvan-esenyurt",
    name: "رستوران کیوان — اسنیورت",
    kind: "RESTAURANT",
    area: "esenyurt",
    address: "Cumhuriyet Mah., Kent Vizyon Sitesi 1B3, Esenyurt/İstanbul",
    mapsQuery: "Keyvan Restaurant Kent Vizyon Esenyurt",
    lat: 41.0342,
    lng: 28.6754,
    phone: "+90 532 424 77 54",
    hours: "۱۰:۰۰–۲۳:۰۰",
    description: "غرب شهر، اسنیورت. برای کسانی که آن سمت زندگی می‌کنند.",
  },
  {
    slug: "atabak-esenyurt",
    name: "رستوران اتابک",
    kind: "RESTAURANT",
    area: "esenyurt",
    address: "Mevlana, Evliya Çelebi Cd. İnciler Pasajı D:4/6, Esenyurt/İstanbul",
    mapsQuery: "Atabak Restaurant Evliya Çelebi Caddesi Esenyurt",
    lat: 41.0268,
    lng: 28.6684,
    phone: "+90 543 447 77 01",
    hours: "۱۲:۰۰–۲۲:۰۰",
    description: "اسنیورت. گاهی موسیقی زنده؛ کلاب شبانه نیست.",
  },
  {
    slug: "zaim-avcilar",
    name: "رستوران زعیم",
    kind: "RESTAURANT",
    area: "avcilar",
    address: "Mustafa Kemal Paşa, D-100 Kuzey Yanyolu, Avcılar/İstanbul",
    mapsQuery: "Zaim İran Restaurant D-100 Avcılar",
    lat: 41.0232,
    lng: 28.7184,
    phone: "+90 541 948 23 23",
    hours: "۱۱:۰۰–۲۳:۰۰",
    description: "آوجیلار، کنار D-100. ناهار و شام ایرانی غرب استانبول.",
  },
  {
    slug: "masihanim-beylikduzu",
    name: "رستوران مسی‌خانم",
    kind: "RESTAURANT",
    area: "beylikduzu",
    address: "Büyükşehir, Atatürk Bulvarı, Beylikdüzü/İstanbul",
    mapsQuery: "Masihanim Restaurant Atatürk Bulvarı Beylikdüzü",
    lat: 41.0024,
    lng: 28.6412,
    phone: "+90 539 650 32 65",
    hours: "۱۲:۰۰–۰۰:۰۰، آخر هفته تا دیرتر",
    description: "بیلیکدوزو. موسیقی زنده؛ نزدیک‌ترین حس «کلاب خانوادگی» ایرانی در غرب.",
  },
  {
    slug: "iran-market-aksaray",
    name: "ایران مارکت — آکسارای",
    kind: "MARKET",
    area: "aksaray",
    address: "Kemalpaşa Mah., Atatürk Bulvarı No:160, Fatih/İstanbul",
    mapsQuery: "İran Market Atatürk Bulvarı 160 Aksaray",
    lat: 41.0126,
    lng: 28.9538,
    hours: "هر روز جز یکشنبه",
    description: "سوپرمارکت ایرانی کنار آسمان. زرشک، سبزی خشک، نان — جای تصادف با هموطن.",
  },
  {
    slug: "iran-market-sisli",
    name: "ایران مارکت — شیشلی",
    kind: "MARKET",
    area: "sisli",
    address: "Cumhuriyet, Kazım Orbay Cd. No:24, Şişli/İstanbul",
    mapsQuery: "Iran Market Kazım Orbay Caddesi 24 Şişli",
    lat: 41.0588,
    lng: 28.9886,
    phone: "+90 555 010 68 84",
    hours: "۱۰:۰۰–۲۱:۰۰، یکشنبه بسته",
    description: "مارکت ایرانی شیشلی/بومونتی. خرید هفتگی و سلام‌علیک.",
  },
  {
    slug: "iran-market-maslak",
    name: "ایران مارکت — ماسلاک",
    kind: "MARKET",
    area: "maslak",
    address: "Maslak Mah., Dereboyu 2. Cad. No:19C, Sarıyer/İstanbul",
    mapsQuery: "Iranian Market Dereboyu 2 Caddesi 19C Maslak",
    lat: 41.1092,
    lng: 29.0072,
    priceRange: "₺–₺₺",
    menuNotes: "زرشک، سبزی خشک، نان لواش، ادویه",
    description: "مارکت ایرانی ماسلاک. برای ساکن‌های شمال شهر.",
  },
  {
    slug: "damo-taksim",
    name: "رستوران دامو — تکسیم",
    kind: "RESTAURANT",
    area: "taksim",
    address: "Katip Mustafa Çelebi, Hocazade Sk. 22/A, 34433 Beyoğlu/İstanbul",
    mapsQuery: "Damo Iranian Restaurant Hocazade Sokak 22 Beyoğlu",
    lat: 41.0356,
    lng: 28.9838,
    phone: "+90 552 355 30 91",
    website: "https://damorestaurant.com",
    hours: "۱۳:۰۰–۲۲:۳۰",
    priceRange: "₺₺₺",
    menuNotes: "چلوکباب، جوجه، خورش؛ فضای شیک نزدیک تکسیم",
    description: "دامو در بی‌اوغلو، چند قدمی تکسیم. غذای ایرانی با دکور مرتب — مناسب دورهمی عصر جمعه.",
  },
  {
    slug: "aydan-esenyurt",
    name: "رستوران آیدان — اسنیورت",
    kind: "RESTAURANT",
    area: "esenyurt",
    address: "Zafer Mah., Adile Naşit Bulvarı, Hep İstanbul Sitesi, 185. Sokak H1 Blok No:19-A, Esenyurt/İstanbul",
    mapsQuery: "Aydan Iranian Restaurant Hep İstanbul Esenyurt",
    lat: 41.0218,
    lng: 28.6694,
    phone: "+90 534 640 00 74",
    website: "http://www.aydanrestaurant.com/",
    hours: "۱۱:۳۰–۲۳:۳۰",
    priceRange: "₺₺",
    menuNotes: "کباب و خورش ایرانی غرب استانبول",
    description: "آیدان در هپ‌استانبول اسنیورت. برای ساکن‌های غرب که نمی‌خواهند تا آکسارای بروند.",
  },
  {
    slug: "shah-kebab-basaksehir",
    name: "شاه کباب — باشاک‌شهر",
    kind: "RESTAURANT",
    area: "basaksehir",
    address: "Bahçeşehir 2. Kısım Mah., Şelale Cad., Hill Park Sitesi No:19/1Z, Başakşehir/İstanbul",
    mapsQuery: "Şah Kebap Şelale Caddesi Hill Park Başakşehir",
    lat: 41.0634,
    lng: 28.6842,
    phone: "+90 553 799 39 99",
    hours: "۱۱:۰۰–۰۰:۰۰",
    priceRange: "₺₺",
    menuNotes: "کباب ایرانی و ترکی؛ اولین پاتوق ایرانی باشاک‌شهر",
    description: "شاه کباب در باغچه‌شهر / باشاک‌شهر. گزینهٔ محلی برای شمال‌غرب استانبول.",
  },
  {
    slug: "tehroon-kadikoy",
    name: "مطبخ تهرون — کادیکوی",
    kind: "RESTAURANT",
    area: "kadikoy",
    address: "Fikirtepe, Özen Sk. No:5, 34720 Kadıköy/İstanbul",
    mapsQuery: "Tehroon Restaurant Özen Sokak 5 Kadıköy Fikirtepe",
    lat: 40.9936,
    lng: 29.0488,
    phone: "+90 850 554 50 50",
    website: "http://matbakhtehroon.com/",
    hours: "۱۲:۰۰–۲۳:۰۰، شنبه تا ۲۲:۳۰",
    priceRange: "₺₺₺",
    menuNotes: "ته‌دیگ، کباب، خورش؛ شعبهٔ آسیایی مطبخ تهرون",
    description: "مطبخ تهرون در فیکیرتپه کادیکوی. کنار شیراز و چشمه برای سمت آسیا.",
  },
  {
    slug: "palmiye-esenyurt",
    name: "رستوران پالمیه — اسنیورت",
    kind: "RESTAURANT",
    area: "esenyurt",
    address: "Nazım Hikmet Bulvarı, 2064. Sk. No:5 D:63, Esenyurt/İstanbul",
    mapsQuery: "Palmiye İran Restaurant Nazım Hikmet Bulvarı Esenyurt",
    lat: 41.0184,
    lng: 28.6628,
    phone: "+90 533 098 19 00",
    hours: "۰۹:۰۰–۲۳:۰۰",
    priceRange: "₺₺",
    menuNotes: "قرمه‌سبزی، فسنجان، چلوکباب",
    description: "پالمیه در اسنیورت/بیلیکدوزو. فضای خانگی ایرانی برای غرب شهر.",
  },
];
