name: Bug
description: Something broken
labels: [bug]
body:
  - type: textarea
    id: expected
    attributes:
      label: Expected
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual
    validations:
      required: true
  - type: input
    id: surface
    attributes:
      label: Surface
      placeholder: api / web / mobile
