/** Shared Persian messages keyed by stable API error.code */
export const ERROR_FA: Record<string, string> = {
  VALIDATION_FAILED: "ورودی ناقص است.",
  AUTH_INVALID_CREDENTIALS: "ایمیل یا رمز اشتباه است.",
  AUTH_EMAIL_TAKEN: "این ایمیل قبلاً ثبت شده.",
  AUTH_LOCKED: "حساب موقتاً قفل است.",
  AUTH_UNAUTHORIZED: "وارد شو.",
  AUTH_FORBIDDEN: "اجازه نداری.",
  AUTH_EMAIL_TOKEN_INVALID: "لینک تأیید منقضی یا نادرست است.",
  AUTH_ACCOUNT_PAUSED: "حساب متوقف است. از سر بگیر تا دوباره بنویسی.",
  AUTH_ACCOUNT_SUSPENDED: "حساب تعلیق شده.",
  EVENT_NOT_FOUND: "رویداد پیدا نشد.",
  EVENT_FULL: "ظرفیت پر است؛ در لیست انتظار هستی.",
  EVENT_CHECKIN_INVALID: "کد ورود درست نیست.",
  EVENT_NOT_GOING: "اول RSVP کن، بعد وارد شو.",
  VENUE_NOT_FOUND: "مکان پیدا نشد.",
  VENUE_MAPS_INVALID: "لینک گوگل‌مپ لازم است.",
  REVIEW_DUPLICATE: "برای این مکان قبلاً نظر داده‌ای.",
  POST_NOT_FOUND: "پست پیدا نشد.",
  FEED_FORBIDDEN: "فقط میزبان و عضو تأییدشده می‌نویسند.",
  MEDIA_NOT_FOUND: "عکس پیدا نشد.",
  MEDIA_INVALID: "عکس پذیرفته نشد.",
  MEDIA_FORBIDDEN: "اجازهٔ دیدن این عکس را نداری.",
  VERIFICATION_INVALID: "تأیید دست‌نویس پذیرفته نشد.",
  VERIFICATION_NOT_FOUND: "درخواست تأیید پیدا نشد.",
  USER_NOT_FOUND: "کاربر پیدا نشد.",
  USER_SELF_ACTION: "این کار روی خودت ممکن نیست.",
  ALREADY_BLOCKED: "قبلاً بلاک شده.",
  REPORT_INVALID: "گزارش پذیرفته نشد.",
  RATE_LIMITED: "چند لحظه صبر کن و دوباره تلاش کن.",
  INTERNAL: "خطای داخلی. دوباره تلاش کن.",
  NETWORK: "اتصال برقرار نشد. همان وای‌فای لپ‌تاپ را چک کن و API روشن باشد.",
};
